version: "3"

networks:
    laravel:

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile.app
        image: laravel/laravel-app
        container_name: laravel-app
        volumes:
            - ./:/var/www
        working_dir: /var/www
        restart: unless-stopped
        networks:
            - laravel

    nginx:
        build:
            context: ./
            dockerfile: Dockerfile.nginx
        image: laravel/laravel-nginx
        container_name: laravel-nginx
        tty: true
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:8080
        working_dir: /var/www
        restart: unless-stopped
        depends_on:
            - app
        networks:
            - laravel
